# production:
#   adapter: mysql
#   database: openmrs
#   username: root
#   password:
#   host: localhost

development:
  adapter: mysql
  database: mateme_development
  username: root
  password: thecool!
  host: localhost

test:
  adapter: mysql
  database: openmrs_test
  username: root
  password: 
  host: localhost


